COMPETITIONS = {
    "v2": [
        {
            "competition_id": 1,
            "season_id": 1,
            "country_name": "Dumnonia",
            "competition_name": "Brythonic Premier League",
            "competition_gender": "male",
            "season_name": "560/561",
            "match_updated": "2020-01-30T02:24:23.296715",
            "match_available": "2020-01-30T02:24:23.296715",
        },
        {
            "competition_id": 1,
            "season_id": 2,
            "country_name": "Dumnonia",
            "competition_name": "Brythonic Premier League",
            "competition_gender": "male",
            "season_name": "561/562",
            "match_updated": "2000-12-01T23:00:00.000000",
            "match_available": "2000-12-01T23:00:00.000000",
        },
        {
            "competition_id": 2,
            "season_id": 2,
            "country_name": "Wessex",
            "competition_name": "Wessex Men's Championship",
            "competition_gender": "male",
            "season_name": "561/562",
            "match_updated": "2000-12-01T23:00:00.000000",
            "match_available": None,
        },
        {
            "competition_id": 3,
            "season_id": 2,
            "country_name": "Wessex",
            "competition_name": "Wessex Women's Championship",
            "competition_gender": "female",
            "season_name": "561/562",
            "match_updated": None,
            "match_available": "2000-12-01T23:00:00.000000",
        },
    ]
}


MATCHES = {
    "v3": [
        {
            "match_id": 1234,
            "match_date": "0640-01-01",
            "kick_off": "15:00:00.000",
            "competition": {
                "competition_id": 4,
                "country_name": "Mercia",
                "competition_name": "League Ān",
            },
            "season": {"season_id": 3, "season_name": "639/640"},
            "home_team": {
                "home_team_id": 101,
                "home_team_name": "Warwick Wanderers",
                "home_team_gender": "male",
                "home_team_group": None,
                "country": {"id": 3, "name": "Mercia"},
            },
            "away_team": {
                "away_team_id": 102,
                "away_team_name": "Tamworth Rovers",
                "away_team_gender": "male",
                "away_team_group": None,
                "country": {"id": 3, "name": "Mercia"},
            },
            "home_score": None,
            "away_score": None,
            "match_status": "scheduled",
            "last_updated": "2019-09-01T10:48:29.321435",
            "metadata": {},
            "match_week": 35,
            "competition_stage": {"id": 1, "name": "Regular Season"},
            "stadium": {
                "id": 383,
                "name": "Eastgate",
                "country": {"id": 3, "name": "Mercia"},
            },
            "referee": {
                "id": 123,
                "name": "None",
            },  # "None" is not a mistake! This is actually what the API returns...
        },
        {
            "match_id": 4321,
            "match_date": "0655-10-15",
            "kick_off": "18:00:00.000",
            "competition": {
                "competition_id": 4,
                "country_name": "Mercia",
                "competition_name": "League Ān",
            },
            "season": {"season_id": 3, "season_name": "655/656"},
            "home_team": {
                "home_team_id": 101,
                "home_team_name": "Warwick Wanderers",
                "home_team_gender": "male",
                "home_team_group": None,
                "country": {"id": 3, "name": "Mercia"},
                "managers": [
                    {
                        "id": 345,
                        "name": "Penda Pybbasen",
                        "nickname": None,
                        "dob": "626-04-01",
                        "country": {"id": 3, "name": "Mercia"},
                    },
                    {
                        "id": 546,
                        "name": "Æthelhere Wuffingas",
                        "nickname": None,
                        "dob": "0627-04-01",
                        "country": {"id": 3, "name": "East Anglia"},
                    },
                ],
            },
            "away_team": {
                "away_team_id": 234,
                "away_team_name": "Whitby United",
                "away_team_gender": "male",
                "away_team_group": None,
                "country": {"id": 4, "name": "Northumbria"},
                "managers": [
                    {
                        "id": 546,
                        "name": "Oswiu, son of Æthelfrith",
                        "nickname": "Oswig",
                        "dob": "0612-02-12",
                        "country": {"id": 4, "name": "Northumbria"},
                    }
                ],
            },
            "home_score": 1,
            "away_score": 3,
            "match_status": "available",
            "last_updated": "2020-02-11T11:18:07.021",
            "metadata": {
                "data_version": "1.1.0",
                "shot_fidelity_version": "2",
                "xy_fidelity_version": "2",
            },
            "match_week": 14,
            "competition_stage": {"id": 1, "name": "Regular Season"},
            "stadium": {
                "id": 234,
                "name": "Cock Beck",
                "country": {"id": 3, "name": "Mercia"},
            },
            "referee": {
                "id": 454,
                "name": "St. Bede",
                "country": {"id": 4, "name": "Northumbria"},
            },
        },
    ]
}


LINEUPS = {
    "v2": [
        {
            "team_id": 9876,
            "team_name": "Some Home Team",
            "lineup": [
                {
                    "player_id": 4546,
                    "player_name": "Some Person",
                    "player_nickname": None,
                    "birth_date": "1992-01-01",
                    "player_gender": "male",
                    "player_height": 173.0,
                    "player_weight": 63.0,
                    "jersey_number": 21,
                    "country": {"id": 11, "name": "Someplace"},
                },
                {
                    "player_id": 6628,
                    "player_name": "Some Person",
                    "player_nickname": "Somey",
                    "birth_date": "1992-01-01",
                    "player_gender": "male",
                    "player_height": 176.0,
                    "player_weight": 73.0,
                    "jersey_number": 10,
                    "country": {"id": 178, "name": "Someplace"},
                },
            ],
        },
        {
            "team_id": 3257463,
            "team_name": "Some Away Team",
            "lineup": [
                {
                    "player_id": 9745,
                    "player_name": "Some Person",
                    "player_nickname": "Somey",
                    "birth_date": "1993-01-01",
                    "player_gender": "male",
                    "player_height": 172.0,
                    "player_weight": 73.0,
                    "jersey_number": 32,
                    "country": {"id": 11, "name": "Someplace"},
                },
                {
                    "player_id": 27341,
                    "player_name": "Some Person",
                    "player_nickname": "Somey",
                    "birth_date": "1986-01-01",
                    "player_gender": "male",
                    "player_height": 166.0,
                    "player_weight": 67.0,
                    "jersey_number": 21,
                    "country": {"id": 45, "name": "Someplace"},
                },
            ],
        },
    ]
}


EVENTS = {
    "v5": [
        {
            "id": "23c72492-5eb6-4f51-a979-0013304763ba",
            "index": 4,
            "period": 1,
            "timestamp": "00:00:00.000",
            "minute": 0,
            "second": 0,
            "type": {"id": 18, "name": "Half Start"},
            "possession": 1,
            "possession_team": {"id": 749, "name": "Team A"},
            "play_pattern": {"id": 1, "name": "Regular Play"},
            "team": {"id": 749, "name": "Team A"},
            "duration": 0.0,
            "related_events": ["1757ab8f-bb38-4085-961e-2c417213677f"],
        },
        {
            "id": "b3c89786-8ab7-47ab-9ad8-8a0f60c32507",
            "index": 5,
            "period": 1,
            "timestamp": "00:00:00.463",
            "minute": 0,
            "second": 0,
            "type": {"id": 30, "name": "Pass"},
            "possession": 2,
            "possession_team": {"id": 966, "name": "Team B"},
            "play_pattern": {"id": 9, "name": "From Kick Off"},
            "team": {"id": 966, "name": "Team B"},
            "player": {"id": 15611, "name": "Player X"},
            "position": {"id": 23, "name": "Center Forward"},
            "location": [60.0, 40.0],
            "duration": 0.472563,
            "related_events": ["1d63288b-bed3-4d99-aaf0-0e6e9bf82b84"],
            "pass": {
                "recipient": {"id": 15547, "name": "Player Y"},
                "length": 1.4866068,
                "angle": 0.8329813,
                "height": {"id": 1, "name": "Ground Pass"},
                "end_location": [61.0, 41.1],
                "type": {"id": 65, "name": "Kick Off"},
                "body_part": {"id": 40, "name": "Right Foot"},
            },
        },
        {
            "id": "1d63288b-bed3-4d99-aaf0-0e6e9bf82b84",
            "index": 6,
            "period": 1,
            "timestamp": "00:00:00.936",
            "minute": 0,
            "second": 0,
            "type": {"id": 42, "name": "Ball Receipt*"},
            "possession": 2,
            "possession_team": {"id": 966, "name": "Team B"},
            "play_pattern": {"id": 9, "name": "From Kick Off"},
            "team": {"id": 966, "name": "Team B"},
            "player": {"id": 15547, "name": "Player Y"},
            "position": {"id": 19, "name": "Center Attacking Midfield"},
            "location": [61.0, 41.1],
            "related_events": ["b3c89786-8ab7-47ab-9ad8-8a0f60c32507"],
        },
        {
            "id": "21ca17d9-2ba7-4aa5-ae08-bfc82ba6785e",
            "index": 7,
            "period": 1,
            "timestamp": "00:00:00.936",
            "minute": 0,
            "second": 0,
            "type": {"id": 43, "name": "Carry"},
            "possession": 2,
            "possession_team": {"id": 966, "name": "Team B"},
            "play_pattern": {"id": 9, "name": "From Kick Off"},
            "team": {"id": 966, "name": "Team B"},
            "player": {"id": 15547, "name": "Player Y"},
            "position": {"id": 19, "name": "Center Attacking Midfield"},
            "location": [61.0, 41.1],
            "duration": 1.418851,
            "under_pressure": True,
            "related_events": [
                "06ecdc24-c95e-4d5b-80d3-f401568bba3c",
                "1d63288b-bed3-4d99-aaf0-0e6e9bf82b84",
                "788fccf5-e07f-4902-a22a-f73b89de7e1a",
            ],
            "carry": {"end_location": [63.4, 35.0]},
        },
    ]
}
